### ISSUE TITLE
On locally launched server any page throws HTTP 500: TemplateNotFound

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#217]
Recent changes to the dpr.py in #212 rendered the locally launched server broken. Application starts silently, but accessing any page results in TemplateNotFound error:
```
(dprapi) u1@linux-1zpk:/home/z/pproj/dpr-api> python dpr.py         
Traceback (most recent call last):
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/gevent/pywsgi.py", line 909, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/pproj/dpr-api/app/site/controllers.py", line 23, in index
    return render_template("index.html"), 200
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/u1/.virtualenvs/dprapi/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: index.html
Mon Jan 30 17:51:13 2017 {'REMOTE_PORT': '57980', 'HTTP_HOST': '127.0.0.1:5000', 'REMOTE_ADDR': '::ffff:127.0.0.1', (hidden keys: 25)} failed with TemplateNotFound

::ffff:127.0.0.1 - - [2017-01-30 17:51:13] "GET / HTTP/1.1" 500 161 0.008889
```

**Comment by subhankarb** [comment]
@Fak3 did you run the following commands https://github.com/frictionlessdata/dpr-api#submodules

**Comment by Fak3** [comment]
yes

**Comment by subhankarb** [comment]
FIXED.
This was a problem when we were in react, and was generating html page from there. But right now we moved to MPA and this html page resides in templates directory. So this is not a problem right now.
Tested and closing

**Comment by rufuspollock** [comment]
@subhankarb as a minor point for future ref I'd suggest this was an INVALID rather than FIXED. Basically, the problem does not exist (or no longer exists). It was not FIXED per se ...

Great you'd checked this.
